[project]
site_name = "My Website"
site_description = "Personal website and blog docs"
site_author = "Patryk Jesionka"

nav = [
  { "Home" = "index.md" },
]

[project.theme]
language = "en"
features = [
  "navigation.sections",
  "navigation.top",
  "search.highlight",
]
